Sender: LSF System <lsfadmin@lo-s4-006>
Subject: Job 427177: <opt10> in cluster <leonhard> Exited

Job <opt10> was submitted from host <lo-login-02> by user <zaziza> in cluster <leonhard> at Tue May 29 17:39:34 2018.
Job was executed on host(s) <lo-s4-006>, in queue <gpu.24h>, as user <zaziza> in cluster <leonhard> at Tue May 29 17:51:38 2018.
</cluster/home/zaziza> was used as the home directory.
</cluster/home/zaziza/AdaptSegNet> was used as the working directory.
Started at Tue May 29 17:51:38 2018.
Terminated at Tue May 29 17:51:39 2018.
Results reported at Tue May 29 17:51:39 2018.

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python train_gta2cityscapes_multi.py --data-dir /cluster/work/riner/users/zaziza/airsim/ --data-list /cluster/work/riner/users/zaziza/airsim/listsOfDataDirs/train_processed_5classes_originalSize_1channel.txt --data-list-target /cluster/work/riner/users/zaziza/isprs/listsOfDataDirs/train_80percent.txt --num-classes 5 --not-restore-last --source airsim --val-every 100 --snapshot-dir /cluster/work/riner/users/zaziza/snapshots/AdaptSegNet/opt10 --lambda-adv-target1 0.0 --lambda-seg 0.0 --dont-train 1,2,3,4 --restore-from /cluster/work/riner/users/zaziza/snapshots/AdaptSegNet/deeplab3/best/model_18.pth
------------------------------------------------------------

Exited with exit code 2.

Resource usage summary:

    CPU time :                                   0.17 sec.
    Max Memory :                                 5 MB
    Average Memory :                             -
    Total Requested Memory :                     100000.00 MB
    Delta Memory :                               99995.00 MB
    Max Swap :                                   -
    Max Processes :                              -
    Max Threads :                                -
    Run time :                                   25 sec.
    Turnaround time :                            725 sec.

The output (if any) follows:

python: can't open file 'train_gta2cityscapes_multi.py': [Errno 2] No such file or directory
